### ISSUE TITLE
libnl issues on Redhat 7.0

### ISSUE THREAD

**Issue by clameter** [Mellanox/libvma#24]
Runnig libvma triggers a bug in libnl that seems to indicate that an invalid module tried to register itself with libnl.

LD_PRELOAD=/usr/local/lib/libvma.so lldiag-0.15/mcast 
mcast: route/tc.c:973: rtnl_tc_register: Assertion `0' failed.

**Comment by rosenbaumalex** [comment]
We're in processes of fixing this. 

Current VMA is dependent on libnl v1.
I'm guessing you're running on a more modern Linux which has libnl v3.

VMA configure step will detect which libnl version is installed on the build machine and run with that version of the libnl interface.
I expect we'll have the fix for this ready in a couple of weeks.

**Comment by clameter** [comment]
Why does the libvma on top of Mellanox OFED not have the issue?

Can we just remove libnl3 from Redhat 7 to fix this issue?

**Comment by rosenbaumalex** [comment]
Fixed by commit https://github.com/Mellanox/libvma/commit/319834aae95404dacd1185f1b1dbce09651bbcae

This commit aligns VMA with libverbs's usage of libnl by adding support for libnl-3.

Please provide feedback.
Note that we're still updating the RPM spec file.
