### ISSUE TITLE
issue using multipacket receive queue API

### ISSUE THREAD

**Issue by eloi29** [Mellanox/libvma#588]
Hi,

We are using libvma on connect x5 to receive multicast RTP streams.
We have a minimal test case with a RTP header parser to detect packet loss.
RTP parsing wokrs fine and detect no packet loss with:

* Libvma vanilla wrapping recv calls
* recvfrom_zcopy

We would like now to use multipacket receive queue and followed your example in the documentation.

We see sometimes that no packets are read. When they are, RTP data is garbage. See logs [logs_mqrp.log] with trace level to 5.

I also attached a sample code used in [test.c.log].
Did you already encounter this issue ?

Best regards,

Eloi

[logs_mprq.log](https://github.com/Mellanox/libvma/files/1796155/logs_mprq.log)
[test.c.log](https://github.com/Mellanox/libvma/files/1796066/test.c.log)

**Comment by rafiw** [comment]
Hi @eloi29 
You are using an advanced feature  – providing more information can help to resolve the issue:
In order to continue I suggest following:
•	please review this part of [vma_extra](https://github.com/Mellanox/libvma/blob/75ba0bd9a4e3f6d83e6c6577e379ed896b54c253/src/vma/vma_extra.h#L252), and read about the [different ways a packet](https://github.com/Mellanox/libvma/blob/75ba0bd9a4e3f6d83e6c6577e379ed896b54c253/src/vma/vma_extra.h#L277) can be written to memory
•	If you still need support please contact nirni@mellanox.com to learn about our support options

**Comment by eloi29** [comment]
Hi,
Thanks for your answer. I actually need to define the receive packet mode to PADDED_PACKET.

I am now able to receive RTP packets. Thanks.

**Comment by liranoz12** [comment]
@eloi29,
Thanks for your feedback!
